service: default
runtime: nodejs10
instance_class: F4
automatic_scaling:
  target_cpu_utilization: 0.70
  target_throughput_utilization: 0.70
  min_idle_instances: 0
  max_idle_instances: 1
  min_instances: 0
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 80
env_variables:
  DATA_ENV: 'development'
  TZ: Asia/Tokyo
handlers:
  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
  - url: /sw.js
    static_files: static/sw.js
    upload: static/sw.js
  - url: /.*
    script: auto
    secure: always

includes:
  - app.env.yaml
