version: 2
jobs:
  comment:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn ts-node ./.ci/report-artifacts.ts
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: bash ./.ci/check-diff.sh
      - run: yarn test:coverage
      - run: yarn build
      - run: yarn build:storybook
      - store_artifacts:
          path: ~/app/storybook-dist
          destination: storybook-dist
      - store_artifacts:
          path: ~/app/coverage
          destination: coverage
      - run: yarn codecov
    dependencies:
      override:
        - yarn add firebase-tools
    deployment:
      deploy:
        branch: master
        commands:
          - firebase deploy --project "connpass-app" --token "1/q-HOjS4q8aPliy1Hyh8mfs8YGjRXAk5FIrK34MEcB3Y"

workflows:
  version: 2
  main:
    jobs:
      - build
      - comment:
          requires:
            - build
